export enum ErrorCode {
  // Audio
  AUDIO_PERMISSION_DENIED = 'AUDIO_PERMISSION_DENIED',
  AUDIO_DEVICE_NOT_FOUND = 'AUDIO_DEVICE_NOT_FOUND',
  AUDIO_CONTEXT_BLOCKED = 'AUDIO_CONTEXT_BLOCKED',
  AUDIO_DECODE_FAILED = 'AUDIO_DECODE_FAILED',

  // Transport
  TRANSPORT_CONNECTION_FAILED = 'TRANSPORT_CONNECTION_FAILED',
  TRANSPORT_CONNECTION_CLOSED = 'TRANSPORT_CONNECTION_CLOSED',
  TRANSPORT_TIMEOUT = 'TRANSPORT_TIMEOUT',

  // Model
  MODEL_SESSION_FAILED = 'MODEL_SESSION_FAILED',
  MODEL_INVALID_CONFIG = 'MODEL_INVALID_CONFIG',
  MODEL_RATE_LIMITED = 'MODEL_RATE_LIMITED',
  MODEL_AUTH_FAILED = 'MODEL_AUTH_FAILED',

  // Tool
  TOOL_TIMEOUT = 'TOOL_TIMEOUT',
  TOOL_UNAVAILABLE = 'TOOL_UNAVAILABLE',
  TOOL_INVALID_RESPONSE = 'TOOL_INVALID_RESPONSE',
  TOOL_VALIDATION_ERROR = 'TOOL_VALIDATION_ERROR',
  // The tool ran and there is no authoritative answer to give: an unpublished price, an
  // unregistered tool. Distinct from BOOKING_NO_AVAILABILITY, which is a statement about
  // the calendar. Both are `NOT_FOUND` at the tool layer and they are not the same fact.
  TOOL_NO_AUTHORITATIVE_ANSWER = 'TOOL_NO_AUTHORITATIVE_ANSWER',

  // Booking & Business
  BOOKING_NO_AVAILABILITY = 'BOOKING_NO_AVAILABILITY',
  BOOKING_CONFLICT = 'BOOKING_CONFLICT',
  BOOKING_FAILED = 'BOOKING_FAILED',
  BOOKING_UNKNOWN_RESULT = 'BOOKING_UNKNOWN_RESULT',
  POLICY_VIOLATION = 'POLICY_VIOLATION',

  // Session & Persona
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  SESSION_ENDED = 'SESSION_ENDED',
  STALE_CONNECTION = 'STALE_CONNECTION',
  PERSONA_INVALID = 'PERSONA_INVALID',
  PERSONA_NOT_FOUND = 'PERSONA_NOT_FOUND',
}
